# Generated by Django 4.2.7 on 2024-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_requires_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_on_get',
            field=models.BooleanField(default=False, verbose_name='Оплата картой'),
        ),
    ]
