# Generated by Django 4.2.7 on 2024-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_is_paid_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_model',
            field=models.CharField(choices=[('CPC', 'За количество щелчков мышью (CPC)'), ('CPM', 'За количество показов (CPM)'), ('CPA', 'За количество действий (CPA)')], default='CPC', max_length=3, verbose_name='Ценовая модель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_model',
            field=models.CharField(choices=[('CPC', 'За количество щелчков мышью (CPC)'), ('CPM', 'За количество показов (CPM)'), ('CPA', 'За количество действий (CPA)')], default='CPC', max_length=3, verbose_name='Ценовая модель'),
        ),
    ]
