# Generated by Django 4.2.7 on 2024-05-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_price_model_alter_orderitem_price_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_model',
        ),
    ]
