# Generated by Django 4.2.7 on 2024-05-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_price_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_on_get',
            field=models.CharField(choices=[('0', 'Карта'), ('1', 'Электронные деньги')], default='0', max_length=1, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_model',
            field=models.CharField(choices=[('CPC', 'За количество щелчков мышью (CPC)'), ('CPM', 'За количество показов (CPM)'), ('CPA', 'За количество действий (CPA)')], default=2, max_length=3, verbose_name='Выбор ценовой модели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_on_get',
            field=models.CharField(choices=[('0', 'Карта'), ('1', 'Электронные деньги')], max_length=1, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_model',
            field=models.CharField(choices=[('CPC', 'За количество щелчков мышью (CPC)'), ('CPM', 'За количество показов (CPM)'), ('CPA', 'За количество действий (CPA)')], max_length=3, verbose_name='Выбор ценовой модели'),
        ),
    ]
