# Generated by Django 4.2.7 on 2024-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_payment_on_get_orderitem_price_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_on_get',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_model',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_on_get',
            field=models.BooleanField(default=False, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_model',
            field=models.BooleanField(default=False, verbose_name='Выбор ценовой модели'),
        ),
    ]
