# Generated by Django 4.2.7 on 2024-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_payment_on_get_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_on_get',
            field=models.CharField(choices=[('card', 'Карта'), ('ewallet', 'Электронные деньги')], max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_model',
            field=models.BooleanField(choices=[('CPC', 'За количество щелчков мышью(СPC)'), ('CPM', 'За количество показов(CPM)'), ('CPA', 'За количество действий(CPA)')], max_length=100, verbose_name='Выбор ценовой модели'),
        ),
    ]
